name: 
  Deploy Project
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        # Download Code    
        - name: Get code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3 #actually already preinstalled on ubuntu
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci #or: install #npm = Node Package Manager: Tool used to install dependencies (third-party packages) for NodeJS project
        - name: Run tests
          run: npm test
  deploy:
    needs: test #Without it both jobs would run in parallel, having a list is also possible
    runs-on: ubuntu-latest #Different jobs can have different runners
    steps:
       # Download Code    
        - name: Get code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3 #actually already preinstalled on ubuntu
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci #or: install #npm = Node Package Manager: Tool used to install dependencies (third-party packages) for NodeJS project
        - name: Build Project
          run: npm run build #build the project
        - name: deploy
          run: echo "Deploying ..."