name:
    Output Information
on:
    workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Outut GitHub context
              run: echo "github${{ toJSON(github) }}" #